Support request.query decoding
Kuadrant/wasm-shim pull request #126
Opened 2024-10-29 19:09 UTC by alexsnaps

See test, but this effectively works like this, given the query string `param1=%F0%9F%91%BE%20&param2=Exterminate%21&%F0%9F%91%BE=123&%F0%9F%91%BE=456`

```
urlDecode(request.query)['param1'] == '👾 ' &&
urlDecode(request.query)['param2'] == 'Exterminate!' &&
urlDecode(request.query)['👾'][0] == '123' &&
urlDecode(request.query)['👾'][1] == '456'
```

i.e.:
 - Doesn't trim
 - decodes all utf-8
 - supports lists of values

2024-10-29 21:50 UTC, eguzki requested changes
LGTM

Add some doc and ready to be merged

2024-10-30 00:40 UTC, alexsnaps commented on src/data/cel.rs
> +                    let v = e.get().clone();
Need to check whether `v` is a `Value::List` here. Add to it if it is, otherwise `clone()` and replace the list as we do here.

2024-10-30 09:32 UTC, alexsnaps commented on src/data/cel.rs
> +            "urlDecode(request.query) == {'👾': ''}
Should this return a `Value::String` ?

2024-10-30 09:32 UTC, alexsnaps commented
@guicassolato so this works for your use-case(s)?
Also, that [last test](https://github.com/Kuadrant/wasm-shim/pull/126/files#r1822212963) is somewhat sad... wdy'all think?

2024-10-30 10:31 UTC, didierofrivia approved these changes
👾

2024-11-05 19:36 UTC, alexsnaps commented
So reading this: 

```
// If a query param is repeated in an HTTP request, the behavior is
// purposely left undefined, since different data planes have different
// capabilities. However, it is *recommended* that implementations should
// match against the first value of the param if the data plane supports it,
// as this behavior is expected in other load balancing contexts outside of
// the Gateway API.
//
// Users SHOULD NOT route traffic based on repeated query params to guard
// themselves against potential differences in the implementations.
```

Wondering if we shouldn't always have the first param in our `Map` and drop the `List` altogether... 
I have a PR getting ready that would: 

```go
fmt.Sprintf("decodeQueryString(request.query)['%s'] == '%s'", queryParam.Name, queryParam.Value)
``` 

@guicassolato do you have an opinion?

2024-11-05 19:38 UTC, alexsnaps commented
Alternate proposal, that I'll implement here right now, pass an optional 2nd bool param, that would dictate whether to return a `List` when repeated params are present, or only the first one (`includeRepeatedParams: bool` kinda thing).

2024-11-07 10:09 UTC, eguzki commented
In description it says `decodeQueryString` but in the implementation I see `queryMap`.

2024-11-07 11:14 UTC, eguzki approved these changes

2024-11-07 11:27 UTC, merged