[DO NOT MERGE YET] External Auth ~ish
Kuadrant/wasm-shim pull request #92
Opened 2024-10-01 16:21 UTC by didierofrivia

This huge PR addresses part of https://github.com/Kuadrant/wasm-shim/issues/58 ... However, all the previous PRs pointing to this branch were thoroughly reviewed **(?).** 

Even if we are only certifying that Rate Limiting works, it's prepared for Auth too. We will close the issue when we provide documentation and deliver it along proper integration tests

## List of the main PRs:

* [x] https://github.com/Kuadrant/wasm-shim/pull/64
* [ ] https://github.com/Kuadrant/wasm-shim/pull/65
* [ ] https://github.com/Kuadrant/wasm-shim/pull/66
* [ ] https://github.com/Kuadrant/wasm-shim/pull/67
* [ ] https://github.com/Kuadrant/wasm-shim/pull/69
* [ ] https://github.com/Kuadrant/wasm-shim/pull/77
* [ ] https://github.com/Kuadrant/wasm-shim/pull/78
* [ ] https://github.com/Kuadrant/wasm-shim/pull/81
* [ ] https://github.com/Kuadrant/wasm-shim/pull/86
* [ ] https://github.com/Kuadrant/wasm-shim/pull/87
* [ ] https://github.com/Kuadrant/wasm-shim/pull/90
* [ ] https://github.com/Kuadrant/wasm-shim/pull/91

## Config example

```yaml
---
extensions:
  limitador:
    type: ratelimit
    endpoint: limitador-cluster
    failureMode: deny
policies:
  - name: rlp-ns-A/rlp-name-A
    hostnames:
      - '*.toystore.com'
      - example.com
    rules:
      - conditions:
          - selector: request.path
            operator: eq
            value: /admin/toy
          - selector: request.method
            operator: eq
            value: POST
          - selector: request.host
            operator: eq
            value: cars.toystore.com
    actions:
      - extension: limitador
        scope: rlp-ns-A/rlp-name-A
        data:
          - static:
              key: rlp-ns-A/rlp-name-A
              value: "1"
          - selector:
              selector: auth.metadata.username
```

## Verification:

Use the new guide in the README to verify multi-action setup:

```
make build && make local-setup
```

Port-forward envoy and watch the logs for all services:
```
kubectl port-forward --namespace default deployment/envoy 8000:8000
kubectl logs -f deployment/envoy
kubectl logs -f deployment/authorino
kubectl logs -f deployment/limitador
```

Test the authenticated rate limiting:
```
curl -H "Host: test.a.multi.com" http://127.0.0.1:8000/get -i
# HTTP/1.1 401 Unauthorized
```

Alice has 5 requests per 10 seconds:
```
while :; do curl --write-out '%{http_code}\n' --silent --output /dev/null -H "Authorization: APIKEY IAMALICE" -H "Host: test.a.multi.com" http://127.0.0.1:8000/get | grep -E --color "\b(429)\b|$"; sleep 1; done
```

Bob has 2 requests per 10 seconds:
```
while :; do curl --write-out '%{http_code}\n' --silent --output /dev/null -H "Authorization: APIKEY IAMBOB" -H "Host: test.a.multi.com" http://127.0.0.1:8000/get | grep -E --color "\b(429)\b|$"; sleep 1; done
```

2024-10-01 18:51 UTC, eguzki commented
Have you considered in squashing commits? Is it worth 72 commits? Up to you.

2024-10-01 18:53 UTC, eguzki requested changes

2024-10-01 18:53 UTC, eguzki commented on README.md
> +extensions:
This example is outdated

2024-10-02 08:44 UTC, adam-cattermole approved these changes
Lgtm

2024-10-02 09:24 UTC, merged